title: Townies Barbershop
email: bostoncolin617@yahoo.com
description: >-
  Great haircuts, great prices.
url: ""

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"